language: python
python:
  - "3.9"

services:
  - docker

before_script: pip install docker-compose

# env: DJANGO_SETTINGS_MODULE="config.settings.travis"

script:
  - cd mycookbook-api
  - docker-compose -f docker-compose.travis.yml run --rm app sh -c "python manage.py test && flake8"