language: python
python:
  - "3.9"

services:
  - docker

before_script: pip install docker-compose

script:
  - cd app
  - docker-compose run --rm app sh -c "coverage run --source='.' manage.py test && flake8"